/**
 * РЕГРЕССИЙН ТЕСТ — production дээр гарсан БОДИТ гуйвуулалтууд.
 *
 * Энд байгаа хос бүр (эх сурвалж → бидний буруу текст) нь 2026-09-27…09-29-нд
 * уншигчид хүрсэн жинхэнэ алдаа. Шалгалтын дүрмийг сулруулах бүрд энэ файл
 * ажиллана: **нэг ч хос «ноцтой»-оос буурч болохгүй**.
 *
 * Мөн эсрэг талыг нь барина: дүрэм хэт хатуу болж ҮНЭНЧ текстийг зогсоовол
 * гаралт хоосорно. Тиймээс «худал эерэг» гэж тогтоогдсон хоёр жишээ «анхаарах»
 * түвшинд үлдэх ёстой — нийтлэхийг зогсоохгүй, харин тайланд гарна.
 */
import { test } from "node:test";
import assert from "node:assert/strict";
import { hardensLegal, speculationVerdict } from "./fidelity.api";
import { blocking, checkBeforePublish } from "./prepublish.api";

// ═══ Эх сурвалжууд (бодит sourceText-ийн гол хэсгүүд) ═══

/** Futurism, 2026-09-21 — Пентагоны мэдээ */
const PENTAGON_SRC =
  "According to new reporting by Bloomberg, the Pentagon's investigation into the February 28th " +
  "air strikes on the Shajareh Tayyebeh girls' school — a double-tap strike which killed over " +
  "150 people, including at least 123 children — concluded that the attack was the result of " +
  "outdated intelligence and over-reliance on an AI targeting system. Interviewed by Bloomberg, " +
  "anonymous military investigators characterized the horrifying attack as the result of a series " +
  "of small errors. Those errors seem to have been compounded by an as-yet unidentified AI " +
  "targeting system, likely similar to the one used by American military officers to fast-track " +
  "air strikes on over 2,000 Iranian targets within a four-day window. The latest info directly " +
  "refutes president Donald Trump's own narrative around the deadly incident. In July, Trump " +
  "downplayed the United States' responsibility for the attack, even suggesting that images and " +
  "footage of the massacre could have been generated by AI. Yet as a UN fact-finding commission " +
  "wrote in its report last week, there are \"reasonable grounds\" to conclude the US attacks " +
  "amount to \"war crimes\".";

/** The Verge AI, 2026-09-25 — Австралийн мэдээ (эх нь болгоомжлолтой) */
const AUSTRALIA_SRC =
  "An OpenAI agent appears to have accessed an Australian government Medicare statistics portal " +
  "without authorisation, the prime minister said. Officials said it was possibly the first " +
  "incident of its kind, though it is unclear whether any data was exfiltrated. The agency may " +
  "have logged additional access attempts.";

/** MIT Technology Review, 2026-09-21 — хилийн камерын мэдээ */
const BORDER_SRC =
  "But dozens suffered slow deaths of exposure in the wilderness, deaths that might have been " +
  "averted with emergency aid. Found in July 2023: Marcia Dutra, a 36-year-old woman from Brazil " +
  "who likely died of heat exposure next to a border fence. It is unclear how many of the towers " +
  "were operational at the time.";

// ═══ 1. БОДИТ ГУЙВУУЛАЛТ — «ноцтой»-оос буурч БОЛОХГҮЙ ═══

test("БОДИТ: Трамп «downplayed / could have» → «үгүйсгэж / мэдэгдсэн / няцаав»", () => {
  // Эх: хариуцлагыг БАГА ҮНЭЛСЭН, бичлэгийг AI-аар хийсэн БАЙЖ БОЛЗОШГҮЙ гэж САНАЛ БОЛГОСОН.
  // Манай текст: ҮГҮЙСГЭСЭН, ХУУРАМЧ ГЭЖ МЭДЭГДСЭН, ба албаны шалгалт НЯЦААСАН.
  const wrong =
    "Ерөнхийлөгч Дональд Трамп өмнө нь тус хэргийн хариуцлагыг үгүйсгэж, бичлэгийг хиймэл " +
    "оюунаар хийсэн хуурамч дүрс гэж мэдэгдэж байсан ч албаны шалгалт үүнийг няцаав.";
  assert.equal(
    speculationVerdict(wrong, PENTAGON_SRC),
    "ноцтой",
    "ишлэлтэй эхний хэсэг нь ишлэлгүй «няцаав»-ыг далдалж болохгүй",
  );
});

test("БОДИТ: «reasonable grounds» → «бүрэн үндэслэлтэй»", () => {
  const wrong =
    "НҮБ-ын баримт шалгах комисс тус агаарын цохилтыг дайны гэмт хэрэг гэж үзэх бүрэн " +
    "үндэслэлтэйг онцоллоо.";
  assert.equal(hardensLegal(wrong, PENTAGON_SRC), true);
});

test("БОДИТ: зассан хувилбар нь хоёуланг нь өнгөрнө", () => {
  const fixed =
    "НҮБ-ын баримт шалгах комисс тус агаарын цохилтыг дайны гэмт хэрэг гэж үзэх үндэслэлтэй " +
    "шалтгаан бийг тайландаа дурджээ. Ерөнхийлөгч Дональд Трамп долоодугаар сард тус хэргийн " +
    "хариуцлагыг бага үнэлж, бичлэгийг хиймэл оюунаар хийсэн байж болзошгүй гэж үзэж байсан юм.";
  assert.equal(hardensLegal(fixed, PENTAGON_SRC), false);
  assert.equal(speculationVerdict(fixed, PENTAGON_SRC), null);
});

test("БОДИТ: нийтлэл бүхэлдээ «ноцтой» гэж баригдана", () => {
  const issues = checkBeforePublish({
    titleMn: "АНУ хиймэл оюунд найдаж сургууль цохисныг Пентагон тогтоов",
    summaryMn:
      "АНУ-ын арми хиймэл оюуны системд хэт найдсанаас болж охидын сургуулийг бөмбөгдөн 150 " +
      "гаруй хүний аминд хүрснийг Пентагоны дотоод шалгалтаар тогтоожээ.",
    bodyMn:
      "Пентагоны дотоод шалгалтаар АНУ-ын зэвсэгт хүчин 2026 оны хоёрдугаар сарын 28-нд охидын " +
      "сургуулийг агаараас цохисныг тогтоолоо.\n\n" +
      "## Олон улсын байр суурь\n" +
      "НҮБ-ын баримт шалгах комисс тус агаарын цохилтыг дайны гэмт хэрэг гэж үзэх бүрэн " +
      "үндэслэлтэйг онцоллоо. Ерөнхийлөгч Дональд Трамп өмнө нь тус хэргийн хариуцлагыг " +
      "үгүйсгэж, бичлэгийг хуурамч дүрс гэж мэдэгдэж байсан ч албаны шалгалт үүнийг няцаав.",
    fbHook: null,
    fbText: null,
    sourceText: PENTAGON_SRC,
    publishedAtSource: new Date("2026-09-21T00:00:00Z"),
    sourceName: "Futurism",
  });
  const rules = new Set(blocking(issues).map((i) => i.rule));
  assert.ok(rules.has("дамжуулалт алга"), [...rules].join(", "));
  assert.ok(rules.has("таамаг→баталгаа"), [...rules].join(", "));
  assert.ok(rules.has("хуулийн томьёолол хүчтэй болов"), [...rules].join(", "));
  assert.ok(blocking(issues).length >= 3, `ноцтой ${blocking(issues).length}`);
});

// ═══ 2. ХУДАЛ ЭЕРЭГ — «анхаарах»-аас дээш гарч БОЛОХГҮЙ ═══

test("ХУДАЛ ЭЕРЭГ: «…гэж Ерөнхий сайд мэдэгдэв» нь ҮНЭНЧ ишлэл", () => {
  // Эх сурвалж дээр ч яг тэр хүн тэгж хэлсэн — бид юу ч хүчтэй болгоогүй
  const faithful =
    "OpenAI-ийн хиймэл оюуны агент Австралийн Medicare статистикийн системд зөвшөөрөлгүй " +
    "нэвтэрсэн гэж тус улсын Ерөнхий сайд мэдэгдэв.";
  assert.equal(speculationVerdict(faithful, AUSTRALIA_SRC), "анхаарах");
});

test("ХУДАЛ ЭЕРЭГ: ишлэлтэй нийтлэл --apply-г ЗОГСООХГҮЙ", () => {
  const issues = checkBeforePublish({
    titleMn: "OpenAI-ийн агент Австралийн төрийн системд нэвтэрчээ",
    summaryMn:
      "OpenAI-ийн хиймэл оюуны агент Австралийн Medicare статистикийн системд зөвшөөрөлгүй " +
      "нэвтэрсэн гэж тус улсын Ерөнхий сайд мэдэгдэв.",
    bodyMn: "Энэ нь төрлийн анхны тохиолдол байж болзошгүй гэж албаныхан үзэж байна.",
    fbHook: null, fbText: null,
    sourceText: AUSTRALIA_SRC,
  });
  assert.deepEqual(blocking(issues), [], JSON.stringify(issues));
  assert.ok(issues.some((i) => i.severity === "анхаарах"), "тайланд гарсаар байх ёстой");
});

test("ХУДАЛ ЭЕРЭГ: «…илрүүлсэн эсэх» нь батлалт БИШ", () => {
  const faithful =
    "АНУ-ын 1 тэрбум гаруй ам.долларын өртөгтэй AI систем нь аюулд орсон хүмүүсийг илрүүлж " +
    "чадахгүй байгаа эсэх, эсвэл илрүүлсэн ч тусламж хүрдэггүй эсэх нь тодорхойгүй хэвээр байна.";
  assert.equal(speculationVerdict(faithful, BORDER_SRC), null);
});

// ═══ 3. Сулруулалтын хамгаалалт ═══

test("ишлэл нь ЗӨВХӨН тухайн хэсгийг чөлөөлнө", () => {
  // Нэг өгүүлбэрт ишлэлтэй ба ишлэлгүй хоёр мэдэгдэл байвал ноцтой хэвээр
  assert.equal(
    speculationVerdict("Сайд мэдэгдэв, харин шалгалт үүнийг няцаав.", PENTAGON_SRC),
    "ноцтой",
  );
});

test("ишлэлгүй шууд батлалт үргэлж ноцтой", () => {
  assert.equal(
    speculationVerdict("Пентагон энэ явдлыг хиймэл оюуны буруу гэж тогтоов.", PENTAGON_SRC),
    "ноцтой",
  );
});

test("дамжуулалтаа хадгалсан бол зөрчил биш", () => {
  assert.equal(
    speculationVerdict("Bloomberg-ийн мэдээлснээр Пентагоны шалгалт ингэж дүгнэжээ.", PENTAGON_SRC),
    null,
  );
});
